# This file was generated by GoReleaser. DO NOT EDIT.
cask "ignr" do
  name "ignr"
  desc "Offline-first gitignore generator"
  homepage "https://github.com/seanlatimer/ignr-cli"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ignr"

  on_macos do
    on_intel do
      url "https://github.com/seanlatimer/ignr-cli/releases/download/v#{version}/ignr-cli_Darwin_x86_64.tar.gz"
      sha256 "1540946bc6b78b2bdaa7a6a45f6cb92b9592b51c5c21c86158e2e5f2fca6acbd"
    end
    on_arm do
      url "https://github.com/seanlatimer/ignr-cli/releases/download/v#{version}/ignr-cli_Darwin_arm64.tar.gz"
      sha256 "b21d7fd36633a06b8c1eda40c99f1c92291e5d2a9229644325c84df96c40db12"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/seanlatimer/ignr-cli/releases/download/v#{version}/ignr-cli_Linux_x86_64.tar.gz"
      sha256 "0a83a5167a63ecfeba751faf6663607c3499d755597f57a63818303748d16075"
    end
    on_arm do
      url "https://github.com/seanlatimer/ignr-cli/releases/download/v#{version}/ignr-cli_Linux_arm64.tar.gz"
      sha256 "41299e7a537bbb8a1ffa4c106f7395d1e16e780854690bebc5b6e0d5b0ef2ce3"
    end
  end

  # No zap stanza required
end
