# This file was generated by GoReleaser. DO NOT EDIT.
cask "op-s3-credentials" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "3e956a078dfb10dc0c4031204309a2ef5131beb9d0cfdf9fed52fb85b6177819"
      url "https://github.com/SeanLatimer/op-s3-credentials/releases/download/v#{version}/op-s3-credentials_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5597c4d280c2cf1bfaff160bd22e22ef61091d51e14a1eaf8509de23ae56fbdd"
      url "https://github.com/SeanLatimer/op-s3-credentials/releases/download/v#{version}/op-s3-credentials_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c1b622ba9ad29675b84f54be3b75aea2815d26c7a058a0839749b622faf3f324"
      url "https://github.com/SeanLatimer/op-s3-credentials/releases/download/v#{version}/op-s3-credentials_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fa764d090ad57d95b2204d90a555809b6f0ca1778454ed76acfc33f7a15253d1"
      url "https://github.com/SeanLatimer/op-s3-credentials/releases/download/v#{version}/op-s3-credentials_linux_amd64.tar.gz"
    end
  end

  name "op-s3-credentials"
  desc "AWS credential_process helper backed by 1Password"
  homepage "https://github.com/SeanLatimer/op-s3-credentials"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "op-s3-credentials"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/op-s3-credentials"]
    end
  end

  # No zap stanza required
end
